[Cancer arises in the context of an in vivo tumor microenvironment., This microenvironment
    is both a cause and consequence of tumorigenesis., 'Tumor and host cells co-evolve
    dynamically through indirect and direct cellular interactions, eliciting multiscale
    effects on many biological programs, including cellular proliferation, growth,
    and metabolism, as well as angiogenesis and hypoxia and innate and adaptive immunity.',
  Here we highlight specific biological processes that could be exploited as targets
    for the prevention and therapy of cancer., 'Specifically, we describe how inhibition
    of targets such as cholesterol synthesis and metabolites, reactive oxygen species
    and hypoxia, macrophage activation and conversion, indoleamine 2,3-dioxygenase
    regulation of dendritic cells, vascular endothelial growth factor regulation of
    angiogenesis, fibrosis inhibition, endoglin, and Janus kinase signaling emerge
    as examples of important potential nexuses in the regulation of tumorigenesis
    and the tumor microenvironment that can be targeted.', 'We have also identified
    therapeutic agents as approaches, in particular natural products such as berberine,
    resveratrol, onionin A, epigallocatechin gallate, genistein, curcumin, naringenin,
    desoxyrhapontigenin, piperine, and zerumbone, that may warrant further investigation
    to target the tumor microenvironment for the treatment and/or prevention of cancer.']
